server:
  port: 9500
  

spring:
  application:
    name: product-service-in-production-environment
  data:
    mongodb:
      database: products
      host: 192.168.99.100
      port: 27017
      
      
#To Manage configuration at run time we can use spring.config.additional-location property

# java -jar product-0.0.1-SNAPSHOT.jar --spring.config.additional-location=C:\Users\srihari.g\Desktop\product-currencies.yml

# custom properties
product:
  currencies:
  - INR
  - USD
  - EUR
  
