server:
  port: 4444
  

spring:
  application:
    name: product-service
  profiles:    active: local  # if profile not found means it runs in default profile
  data:
    mongodb:
      database: products
      host: 192.168.99.100
      port: 27017
   # spring boot admin server      boot:    admin:      client:        url:        - http://localhost:8082
#To Manage configuration at run time we can use spring.config.additional-location property

# java -jar product-0.0.1-SNAPSHOT.jar --spring.config.additional-location=C:\Users\srihari.g\Desktop\product-currencies.yml

# custom properties
product:
  currencies:
  - INR
  - USD
  - EUR
  
  
# log config
logging:  file:    name: e:/logs/product.log
  level: 
    root: INFO    logback:    rollingpolicy:      max-file-size: 50MB        
        
# actuator config   

management:  endpoints:    web:      exposure:        include:        - '*'
  endpoint:    health:      show-details: always
     # to disable mongo status
  health:
    mongo:      enabled:  false 
      
info:
  app:
    name: Product Microservice
    version: 1.0
    desccription: Add and retrieve product information     