server:
  port: 1010
  
spring:
  application:
    name: Fixed-Assests
   
 # datasources details      
  datasource:
    url: jdbc:h2:mem:testdb
    password: sa
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    
# datasources details
  h2:
    console:
      enabled: true
      path: /h2-console
    
    
# actuator specific

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: ALWAYS
      
info:
  app:
    name: Fixed-Assests service
    version: 1.0
    desccription: Add and retrieve Fixed-Assests information